"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# デフォルトの 500ms だとタイムアウトする言語がたまにあるので
command_timeout = 1000

[directory]
# 開発リポジトリを ~/dev/src/{owner}/{repo} に置いているから
truncation_length = 5
