"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# デフォルトの 500ms だとタイムアウトする言語がたまにあるので
command_timeout = 1000

# デフォルトシンボルだと Vim の :terminal でずれが発生する
# vim-ambiwidth で2文字幅に設定され通常のターミナルと比べると幅が大きくなる
# 幅が大きいだけなら良いが Tab による補完を実行した時に何故か幅が小さくなる
# これが気になるので symbol は Plain Text Symbols プリセットで指定されているものに変更
# https://starship.rs/ja-JP/presets/plain-text
[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"


[directory]
# 開発リポジトリを ~/dev/src/{owner}/{repo} に置いているから
truncation_length = 5
